name: chat_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  #Random String
  random_string: ^2.3.1
  #Local Datas
  shared_preferences: ^2.2.0
  #Date Format
  intl: ^0.18.1
  #Indicator
  smooth_page_indicator: ^1.1.0


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/
